spring.application.name=eventos
spring.datasource.url=jdbc:oracle:thin:@mhs8ce7tyhmkhxcm_high?TNS_ADMIN=/2025/Wallet_MHS8CE7TYHMKHXCM
spring.datasource.username=ADMIN
spring.datasource.password=Fullstack-DSY2201
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# Spring.jpa.properties.hibernate.format_sql=true

# logging.level.org.hibernate=DEBUG
# logging.level.com.zaxxer.hikari=DEBUG
# logging.level.java.sql=DEBUG